name: "Test commit"
on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Install nix
      uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        install_url: https://github.com/miuirussia/nix-unstable-installer/releases/latest/download/install
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v12
      with:
        name: yandex-browser-nix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Test browser build
      run: |
        set -x
        nix build .#yandex-browser-stable
        nix build .#yandex-browser-beta
          
